# kind       Version
# Pod         v1
# Service     v1
# ReplicaSet  app/v1
# Deployment  app/v1

apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end

spec:
  containers:
    - name: nginx-container
      image: nginx

# kubectl create -f prova.yaml